### ISSUE TITLE
huge performance decreese between 0.4.0 and 0.5.0

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/PythonQwt#26]
0.4.0
------

Curve benchmark example:

Click on each tab to test if plotting performance is acceptable in terms of GUI response time (switch between tabs, resize main windows, ...).

Benchmarks results: 

100 points:
Elapsed time: 530 ms

1000 points:
Elapsed time: 473 ms

10000 points:
Elapsed time: 399 ms

100000 points:
Elapsed time: 638 ms

1000000 points:
Elapsed time: 2090 ms

Total elapsed time: 4238 ms

0.5.0
-------

Curve benchmark example:
(base plotting library: PythonQwt)

Click on each tab to test if plotting performance is acceptable in terms of GUI response time (switch between tabs, resize main windows, ...).

Benchmarks results: 

100 points:
Elapsed time: 649 ms

1000 points:
Elapsed time: 530 ms

10000 points:
Elapsed time: 662 ms

100000 points:
Elapsed time: 2383 ms

1000000 points:
Elapsed time: 18440 ms

Total elapsed time: 22683 ms

**Comment by PierreRaybaut** [comment]
No, that's not a regression: the test itself changed and I'm drawing 11 curves at once instead of one for each of those benchmark tests (see [here]( https://github.com/PierreRaybaut/PythonQwt/blob/master/qwt/tests/CurveBenchmark.py#L48)), that's why the time results cannot be compared directly to the v0.4.0 release.

I'm afraid that this benchmark will not be a good way of comparing release with each other: this test was written to benchmark performance when optimizing things in the latest release, not to compare different versions of PythonQwt.

**Comment by picca** [comment]
Ok maybe your should print the time per curve instead of time per all curves

**Comment by PierreRaybaut** [comment]
See change above, I've added the curves and plots number in the first tab to indicate clearly what the benchmark is about.

**Comment by PierreRaybaut** [comment]
The elapsed time for each plotted curve may have less meaning than what's displayed right now because the overall elapsed time takes into account the time needed to plot the curve but also the time needed to layout the plot widget, plot the scale ticks, and so on.
