### ISSUE TITLE
X-axis scale wrong when plotting "vertically" (e.g. `x = sin(y)`)

### ISSUE THREAD

**Issue by estan** [PierreRaybaut/PythonQwt#34]
Hi,

This is probably due to a misunderstanding on my part, but with the test plot:

``` python
from os import environ
from sys import argv, exit

from numpy import linspace, sin, pi
from PyQt5.QtWidgets import QApplication

environ['QT_API'] = 'pyqt5'

from qwt import QwtPlot, QwtPlotCurve


class TestPlot(QwtPlot):

    def __init__(self, parent=None):
        super(TestPlot, self).__init__("Test Plot", parent)

        self.enableAxis(self.xBottom, False)
        self.enableAxis(self.xTop, True)

        self.curve = QwtPlotCurve('Test Curve')
        self.curve.attach(self)

        y = linspace(0, 2*pi, 500)

        self.curve.setData(sin(y), y)

        self.replot()


if __name__ == '__main__':
    app = QApplication(argv)

    plot = TestPlot()
    plot.resize(300, 1000)
    plot.show()

    exit(app.exec_())
```

I get the output:

![testplot](https://cloud.githubusercontent.com/assets/86675/13631178/7ea18568-e5e3-11e5-9279-5e9e4f76cb47.png)

Notice how the scale on the top X axis is wrong (0-1000, should be 0-1).

Is this a bug? Or what is the correct way of making "vertical" plots like this?

**Comment by estan** [comment]
I tried manually enabling axis auto-scaling with `self.setAxisAutoScale(self.xTop, True)`, but the result was the same. If I manually set the scale with `self.setAxisScale(self.xTop, 0, 1)`, the scale is correct (agrees with the plotted data).

**Comment by estan** [comment]
I realize now that it works for the bottom X axis, if I enable that. So I would say this is a bug? The logic in `updateAxes(..)` needs to take care of all four axes?

**Comment by estan** [comment]
Here is a better example with all axes enabled that illustrates the problem:

```python
from os import environ
from sys import argv, exit

from numpy import linspace, sin, pi
from PyQt5.QtWidgets import QApplication

environ['QT_API'] = 'pyqt5'

from qwt import QwtPlot, QwtPlotCurve


class TestPlot(QwtPlot):

    def __init__(self, parent=None):
        super(TestPlot, self).__init__("Test Plot", parent)

        self.enableAxis(self.xTop, True)
        self.enableAxis(self.yRight, True)

        self.curve = QwtPlotCurve('Test Curve')
        self.curve.attach(self)

        y = linspace(0, 2*pi, 500)

        self.curve.setData(sin(y), y)

        self.replot()


if __name__ == '__main__':
    app = QApplication(argv)

    plot = TestPlot()
    plot.resize(300, 1000)
    plot.show()

    exit(app.exec_())
```

Result:

![testplot](https://cloud.githubusercontent.com/assets/86675/13632050/21dce4d0-e5e8-11e5-8c61-8e09ab179535.png)

Notice the discrepancy between left/right Y axis, and between top/bottom X axis, due to right/top axes not being considered in `QwtPlot.updateAxes(...)`.

**Comment by estan** [comment]
I realized that for my use-case, where I want only the top and right axis visible, I can work around the problem by setting the X axis to `xTop` on my curve. But I'd like to know whether this should still be considered a bug? I would think so, as you could conceivably want to have three or more axes visible, and have them all auto-scaled?

**Comment by PierreRaybaut** [comment]
I'll take a look at it.

**Comment by PierreRaybaut** [comment]
I wrote a new test script (strongly inspired from your first code sample) in order to compare `PyQwt` and `PythonQwt`:

``` python
import numpy as np
import os

from qwt.qt.QtGui import QApplication

if os.environ.get('USE_PYQWT5', False):
    USE_PYQWT5 = True
    from PyQt4.Qwt5 import QwtPlot, QwtPlotCurve
else:
    USE_PYQWT5 = False
    from qwt import QwtPlot, QwtPlotCurve # analysis:ignore

class TestPlot(QwtPlot):
    def __init__(self, parent=None):
        super(TestPlot, self).__init__(parent)
        self.setWindowTitle("PyQwt" if USE_PYQWT5 else "PythonQwt")
        self.enableAxis(self.xBottom, False)
        self.enableAxis(self.xTop, True)
        self.curve = QwtPlotCurve('Test Curve')
        self.curve.attach(self)
        y = np.linspace(0, 2*np.pi, 500)
        self.curve.setData(np.sin(y), y)
        self.replot()

if __name__ == '__main__':
    app = QApplication([])
    plot = TestPlot()
    plot.resize(250, 700)
    plot.show()
    app.exec_()
```

The results are shown in the following table:

| `PyQwt` | `PythonQwt` |
| --- | --- |
| Qwt 5 | Qwt 6 |
|![image](https://user-images.githubusercontent.com/1311787/89648658-d8732780-d8bf-11ea-8c45-54e07349071d.png)|![image](https://user-images.githubusercontent.com/1311787/89648689-e3c65300-d8bf-11ea-9842-67e5f0509983.png)|

In other words, there is no regression from `PyQwt` to `PythonQwt`... there is even some improvement (probably due to the migration from Qwt v5 to Qwt v6) as the curve is drawn directly below the top axis. In both cases, the curve X-axis has not been set: it is thus associated to the default X-axis, i.e. the bottom X-axis. In other words, the top X-axis is not associated to any plot item: that's why the scale is set to default values (0...1000).
To assign the curve to top X-axis (instead of bottom X-axis), simply use the `setXAxis` method:
``` python
        # [...]
        self.curve = QwtPlotCurve('Test Curve')
        self.curve.setXAxis(self.xTop) # <-------------
        self.curve.attach(self)
        # [...]
```
The result will be the exact opposite: top X-axis will show -1...1 values, whereas bottom X-axis will show the default 0...1000 scale.

**Comment by estan** [comment]
Thanks a lot for clarifying.
